services:
  discord-bot:
    container_name: discord_bot
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-REPLACE_ME}
    ports:
      - '8008:8008'
    restart: unless-stopped
